title: User Styles
subtitle: for the Stylus extension
author: Blockhead25688
avatar: https://avatars1.githubusercontent.com/u/29781372?s=96
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed
